### ISSUE TITLE
make_list.py requires running from utils folder

### ISSUE THREAD

**Issue by Tw1sm** [Tw1sm/spraycharles#16]
`make_list.py` only checks the current working directory for `list_elements.json`. Need to add a quick check for the file in cwd and `utils/` so that it can be run from the main spraycharles folder as the README shows.

**Comment by puzzlepeaches** [comment]
Working on this. I think I am going to add make_list, analyze and ntlm_challenger run as sun-commands of spraycharles itself using click. 

This will be especially useful when I finish the port of spraycharles to a command line utility as opposed to a standalone script.

**Comment by Tw1sm** [comment]
Sounds great, I will leave this one alone then!

**Comment by puzzlepeaches** [comment]
This should now be addressed in #17. Can close this out when we merge.

**Comment by Tw1sm** [comment]
Fixed in master with merge of `pypi` branch 9022fb2d2d0bc443b5d7805d8d03af7c98ab0eb2
